import { GlossaryEntry } from '../types';

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: 'Commit',
    tag: 'Core',
    plainEnglish: 'A permanent snapshot of your project at a specific moment in time. Every commit has a unique SHA hash fingerprint.',
    technicalDetails: 'An immutable Git object pointing to a root Tree object, zero or more parent commit SHAs, author metadata, and a log message.',
    safetyNotice: '🟢 Safe to create. Rewriting existing public commits with amend/rebase is Caution 🟡.',
    relatedCommands: ['git commit', 'git commit -m', 'git commit --amend'],
  },
  {
    term: 'HEAD',
    tag: 'Core',
    plainEnglish: 'The "You Are Here" pointer in Git. It tracks which commit or branch your working folder is currently looking at.',
    technicalDetails: 'A symbolic ref (usually pointing to refs/heads/<branch>) or a direct 40-character commit SHA (detached HEAD).',
    safetyNotice: '🟢 Safe. Moving HEAD simply changes your viewing perspective.',
    relatedCommands: ['git switch', 'git checkout'],
  },
  {
    term: 'Detached HEAD',
    tag: 'Core',
    plainEnglish: 'A state where your HEAD is pointing directly to a specific commit instead of a named branch. You can explore without changing any branch.',
    technicalDetails: 'State where `.git/HEAD` contains a raw commit hash rather than a symbolic reference to a branch pointer.',
    safetyNotice: '🟡 Caution: Any new commits made in Detached HEAD will become orphans unless you create a branch to keep them.',
    relatedCommands: ['git checkout <sha>', 'git switch -c <new-branch>'],
  },
  {
    term: 'Branch',
    tag: 'Branching',
    plainEnglish: 'A lightweight movable label that points to the latest commit on a line of development. Branches let you work on new features without breaking main.',
    technicalDetails: 'A 41-byte text file inside `.git/refs/heads/` containing the 40-character SHA-1 hash of its tip commit.',
    safetyNotice: '🟢 Creating and switching branches is safe.',
    relatedCommands: ['git branch', 'git switch', 'git switch -c'],
  },
  {
    term: 'Fast-Forward Merge',
    tag: 'Branching',
    plainEnglish: 'A merge where Git simply moves the branch pointer forward because no diverging commits occurred on the destination branch.',
    technicalDetails: 'Occurs when the target branch commit is an exact ancestor of the source commit. No new merge commit object is generated.',
    safetyNotice: '🟢 Safe. Preserves a clean linear history.',
    relatedCommands: ['git merge <branch>'],
  },
  {
    term: 'Three-Way Merge',
    tag: 'Branching',
    plainEnglish: 'A merge between two diverged branches where Git finds the common ancestor and creates a new merge commit combining both histories.',
    technicalDetails: 'Uses 3 commit snapshots (Base, Ours, Theirs) to compute diffs and produce a new commit node with 2 parent pointers.',
    safetyNotice: '🟡 Caution: May require conflict resolution if both branches changed identical lines.',
    relatedCommands: ['git merge <branch>'],
  },
  {
    term: 'Rebase',
    tag: 'Branching',
    plainEnglish: 'Replaying your branch commits on top of another branch tip, producing a clean, straight-line history as if you wrote them today.',
    technicalDetails: 'Calculates the range of commits, detaches them, and creates brand new duplicate commit objects with new parent pointers.',
    safetyNotice: '🟡 Caution: Rewrites commit SHAs. Never rebase commits that have already been pushed to a shared public branch.',
    relatedCommands: ['git rebase <upstream>', 'git rebase -i HEAD~3'],
  },
  {
    term: 'Staging Area (Index)',
    tag: 'Core',
    plainEnglish: 'The preparation dock where you gather and review changes before packaging them into a permanent commit snapshot.',
    technicalDetails: 'A binary cache file (`.git/index`) containing staged file paths, mode flags, and SHA-1 blob references.',
    safetyNotice: '🟢 Safe. Staging and unstaging does not alter your saved commit history.',
    relatedCommands: ['git add', 'git restore --staged', 'git status'],
  },
  {
    term: 'Stash',
    tag: 'Internals',
    plainEnglish: 'A temporary storage drawer where you can quickly hide messy, unfinished work to switch branches cleanly, and retrieve it later.',
    technicalDetails: 'A stack of commit objects referencing index and worktree state snapshots outside the main ref history.',
    safetyNotice: '🟢 Safe. Stashes are kept until explicitly popped or dropped.',
    relatedCommands: ['git stash', 'git stash pop', 'git stash list', 'git stash drop'],
  },
  {
    term: 'Reflog',
    tag: 'Advanced',
    plainEnglish: 'Git\'s safety net diary. It records every single movement of your HEAD pointer, allowing you to recover "lost" commits after hard resets.',
    technicalDetails: 'A local chronological log located in `.git/logs/HEAD` storing old and new SHA targets per operation for 30–90 days.',
    safetyNotice: '🟢 Safe. Reflog is read-only inspection for disaster recovery.',
    relatedCommands: ['git reflog', 'git reset --hard <sha>'],
  },
  {
    term: 'Remote (origin)',
    tag: 'Remotes',
    plainEnglish: 'A version of your repository hosted on a server or service like GitHub or GitLab that you collaborate on with teammates.',
    technicalDetails: 'Named references configured in `.git/config` mapping remote server URLs to local tracking branches (`refs/remotes/origin/*`).',
    safetyNotice: '🟢 Fetching is safe. Pushing with `--force` is 🔴 Destructive.',
    relatedCommands: ['git fetch', 'git pull', 'git push', 'git remote -v'],
  },
];
